redguardtoo/evil-matchit

- evil-matchit-org.el
It seems `org-edit-src-find-region-and-lang` is gone in Org 8.3.2. I've scanned the org-mode repo and org-plus-contrib to no avail (aside from two vestigial references, there was no definition). Here is an alternative (perhaps more portable) way to detect the current block's major mode.
> Fix embedded major-mode detection in org-mode

- evil-matchit-ocaml.el
sig/end is a form used in ocaml's module signature language. 
See https://caml.inria.fr/pub/docs/manual-ocaml/moduleexamples.html#sec19 for more information about the syntax.
> Add sig/end matching for ocaml

- evil-matchit-ocaml.el
Make ocaml's jump behave more like vim's % (see #80):
```vim
:help %
"Find the next item in this line after or under the cursor and jump to its match."
```
E.g.:
```ocaml
module Stable = struct
...
end
```
will jump to end no matter where you put your cursor on the first line.
For this to fully make sense, however, we'd have to fix evil-matchit in other plugins as well, in particular, the simple one as otherwise it misbehaves:
```ocaml
let n x =
1 + (match x with
| X -> 1
| Y -> 2)
```
If you put your cursor on 1 and hit <kbd>%</kbd> it'll jump to `with`.
I can fix this for ocaml by finding matching parenthesis in the ocaml plugin myself (and not using evil-matchit-simple.el) but I think this should be fixed globally for all of the plugins.
It seems to me that all of the …
> Ocaml improvements

- evil-matchit-org.el
This is convenient when org babel results are in `:results:` `:end:` drawer and especially when the results are long.
> evil-matchit-org: add :results: :end: drawer

- evil-matchit-elixir.el
- def, defp, defmodule, defmacro, cond, if, case, unless are all using do-end
pair
- See also #83
> only keep fn-end and do-else-end pairs

- evil-matchit-ocaml.el
If a keyword is discovered in a value/function name it shouldn't be
considered as a valid keyword. Use tuareg font face to detect good
positions.
> ocaml: improve validation of keywords

- evil-matchit-verilog.el
Added missing bar between package and covergroup keywords.
> Fixed regex in evilmi-verilog-extract-keyword-howtos

- README.org
- evil-matchit.el
spacemacs open jsx-syntax file in typescript-tsx-mode and react-mode, so I add the two modes to evil-matchit
> add support for react-mode and typescript-tsx-mode and update doc

- evil-matchit.el
> Add autoload definition, fixes #97

- evil-matchit-ocaml.el
This is basically a follow-up on https://github.com/redguardtoo/evil-matchit/commit/5ff747a1eff026bc89298f620e1df59da6fe1cd6 to make it work with normal parentheses.
To do this, I had to stop using things like
```
thing-at-point 'word
```
> Ocaml: add normal parentheses support

- evil-matchit-org.el
There is no 'elisp-mode, so we special-case this.
> Treat source blocks labelled as "elisp".

- evil-matchit-ocaml.el
This is based on #108.
It adds support for making `let` match `;;` in ocaml.
> Add double semicolon

- evil-matchit.el
vim considers matchit movments as jump motions. Following that convention makes modifying of start/end tags much easier.
> Mark evilmi-jump-items as a jump motion

- evil-matchit-org.el
evilmi-plugins is defined in evil-matchit.el, which is not loaded by
evil-matchit-org.el.
----
#
> Silence byte-compiler

- evil-matchit-sdk.el
- tests/evil-matchit-tests.el
If the cursor is placed on a group of whitespace followed by a closing item,
`evilmi-sdk-simple-jump` errors with a `scan-error`, due to calling
`scan-sexps`, which, after skipping whitespace, sees a prematurely terminated
expression (a close tag).
Fix that by making the function skip whitespace first, allowing it to see the
correct item character. This is consistent with `evil-jump-item'.
My issue was as follows (with `debug-on-error` enabled):
```java
// Java has no special evilmi-support
class X {
public static void q(int y) {
/* cursor here, `evilmi-jump-items` errors */    }
}
```
With my PR, `evilmi-jump-items` jumps to the correct open brace.
> `evilmi-sdk-simple-jump': skip whitespace

- evil-matchit-sdk.el
After the previous change, if the cursor is before some whitespace followed by a
comment, the latter wouldn't be skipped as was the case previously. This is
because `evilmi-sdk-simple-jump` would skip to the comment, causing
`evilmi-sdk-jumpto-where` to no longer call `scan-sexp` with comment skipping
enabled.
Addresses point 1 [described here](https://github.com/redguardtoo/evil-matchit/pull/130#issuecomment-745101112).
> `evilmi-sdk-simple-jump': skip comments

- evil-matchit.el
For some reason, I can no longer use a byte-compiled evil-matchit because the evil macros are not loaded. Adding this explicit require fixes the problem.
> Fix byte compiling

- evil-matchit.el
Extend existing support for `octave-mode` to `matlab-mode` so that those who prefer `matlab-mode` to `octave-mode` can still enjoy `evil-matchit` goodness :)
> Support matlab-mode

- evil-matchit-verilog.el
Currently identifiers such as `foo_end`, `Xend`, `begin_foo`, etc will be considered begin/end tags in verilog. This PR makes the regex more restrictive so as to avoid matching identifiers most of the time.
> Fix an issue where verilog identifiers could be matched as begin/end token

- evil-matchit.el
This PR makes evil-matchit support the new [tsx-ts-mode](https://github.com/emacs-mirror/emacs/blob/ac7ec87a7a0db887e4ae7fe9005aea517958b778/lisp/progmodes/typescript-ts-mode.el#L433) available in Emacs 29.
> Enable JS/TS/HTML rules for tsx-ts-mode

- evil-matchit.el
Emacs now ship AUCTeX by default, so the default mode for latex is now provided by AUCTeX, named as LaTeX-mode, to replace the old latex-mode provided by tex.el.
In order to be compatible to people who use latex-mode, both shall be preserved.
> Make latex plugin also works for AUCTeX too

- evil-matchit.el
Adds missing 'tree sitter' version entries for typescript and javascript when setting up html tags match.
> feat: html tag support for js/typescript treesitter modes
